// GENERATED by tools/gen-v8diff.py - do not edit.
// Expected outputs captured from: v26.3.1
#include <ctjs.hpp>
#include <cstdio>
#include <string>

static int failures = 0;
static int parse_gaps = 0;

template <ctll::fixed_string Src>
static void run_case(const char * name, const char * expected) {
	if constexpr (!ctjs::script_t<Src>::valid) {
		std::printf("PARSE-GAP %s\n", name);
		++parse_gaps;
	} else {
		auto r = ctjs::script_t<Src>::run({});
		std::string got{r.console()};
		if (!r.ok()) { got += "THROWS " + r.exception_message() + "\n"; }
		if (got != expected) {
			std::printf("FAIL %s\n  v8 : %s  ctjs: %s", name,
			            std::string{expected}.c_str(), got.c_str());
			++failures;
		}
	}
}

int main() {
	run_case<R"v8(const a = 1;
a = 2;
console.log("unreached");
)v8">(R"v8(const-reassignment-throws)v8", R"v8(THROWS TypeError: Assignment to constant variable.
)v8");
	run_case<R"v8(const o = {x: 1};
o.x = 2;
console.log(o.x);
)v8">(R"v8(const-object-mutation-allowed)v8", R"v8(2
)v8");
	run_case<R"v8(console.log(x);
var x = 1;
console.log(x);
)v8">(R"v8(var-hoisting-reads-undefined)v8", R"v8(undefined
1
)v8");
	run_case<R"v8(if (true) { var y = 5; }
console.log(y);
)v8">(R"v8(var-escapes-block)v8", R"v8(5
)v8");
	run_case<R"v8(for (var i = 0; i < 3; i++) { var w = i; }
console.log(i, w);
)v8">(R"v8(var-escapes-for-body)v8", R"v8(3 2
)v8");
	run_case<R"v8(console.log(z);
let z = 1;
)v8">(R"v8(let-tdz-throws)v8", R"v8(THROWS ReferenceError: Cannot access 'z' before initialization
)v8");
	run_case<R"v8(let b = 1;
{ let b = 2; console.log(b); }
console.log(b);
)v8">(R"v8(let-block-scoped)v8", R"v8(2
1
)v8");
	run_case<R"v8(let fs = [];
for (let i = 0; i < 3; i++) { fs.push(function() { return i; }); }
console.log(fs[0](), fs[1](), fs[2]());
)v8">(R"v8(for-let-closures-per-iteration)v8", R"v8(0 1 2
)v8");
	run_case<R"v8(let gs = [];
for (var j = 0; j < 3; j++) { gs.push(function() { return j; }); }
console.log(gs[0](), gs[1](), gs[2]());
)v8">(R"v8(for-var-closures-shared)v8", R"v8(3 3 3
)v8");
	run_case<R"v8(console.log(f());
function f() { return 42; }
)v8">(R"v8(function-hoisting)v8", R"v8(42
)v8");
	run_case<R"v8(var v = "outer";
function g() { console.log(v); var v = "inner"; console.log(v); }
g();
)v8">(R"v8(var-shadows-in-function)v8", R"v8(undefined
inner
)v8");
	run_case<R"v8(var obj = {n: 5};
obj.get = function() { return this.n; };
console.log(obj.get());
)v8">(R"v8(this-in-method)v8", R"v8(5
)v8");
	run_case<R"v8(var obj2 = {n: 7};
obj2.get = function() { return this; };
var f2 = obj2.get;
console.log(f2() === undefined || f2() === globalThis);
)v8">(R"v8(this-lost-on-extraction)v8", R"v8(true
)v8");
	run_case<R"v8(console.log([] + [], [] + 1, 1 + "2", "3" * "4", null + 1, true + true, undefined + 1);
)v8">(R"v8(plus-coercions)v8", R"v8( 1 12 12 1 2 NaN
)v8");
	run_case<R"v8(console.log(null == undefined, null === undefined, NaN == NaN, 0 == "", "0" == false, "" == false, [] == false);
)v8">(R"v8(loose-equality-table)v8", R"v8(true false false true true true true
)v8");
	run_case<R"v8(console.log(null >= 0, null > 0, null == 0);
)v8">(R"v8(relational-null)v8", R"v8(true false false
)v8");
	run_case<R"v8(console.log(typeof undefined, typeof null, typeof 1, typeof "s", typeof true, typeof {}, typeof [], typeof function(){});
)v8">(R"v8(typeof-table)v8", R"v8(undefined object number string boolean object object function
)v8");
	run_case<R"v8(console.log([10, 1, 2].sort());
)v8">(R"v8(array-sort-is-lexicographic)v8", R"v8([ 1, 10, 2 ]
)v8");
	run_case<R"v8(var arr = [];
arr[3] = 1;
console.log(arr.length, arr[0]);
)v8">(R"v8(array-holes-and-length)v8", R"v8(4 undefined
)v8");
	run_case<R"v8(console.log("abc".slice(-2), "abc".indexOf("z"), " a ".trim(), "aaa".replace("a", "b"));
)v8">(R"v8(string-methods-edges)v8", R"v8(bc -1 a baa
)v8");
	run_case<R"v8(console.log(0.1 + 0.2, 1e21, 1e-7, -0, 1 / 0, -1 / 0, 0 / 0);
)v8">(R"v8(number-printing)v8", R"v8(0.30000000000000004 1e+21 1e-7 -0 Infinity -Infinity NaN
)v8");
	run_case<R"v8(var t = (1, 2, 3);
console.log(t, t > 2 ? "big" : "small");
)v8">(R"v8(ternary-and-comma)v8", R"v8(3 big
)v8");
	run_case<R"v8(console.log(0 || "fallback", 1 && "yes", null ?? "coalesced");
)v8">(R"v8(logical-value-returns)v8", R"v8(fallback yes coalesced
)v8");
	run_case<R"v8(var c = 5;
console.log(c++, c, ++c, c);
)v8">(R"v8(increment-semantics)v8", R"v8(5 6 7 7
)v8");
	run_case<R"v8(var d = {k: 1};
console.log("k" in d);
delete d.k;
console.log("k" in d, d.k);
)v8">(R"v8(delete-and-in)v8", R"v8(true
false undefined
)v8");
	run_case<R"v8(switch (2) {
  case 1: console.log("one");
  case 2: console.log("two");
  case 3: console.log("three"); break;
  case 4: console.log("four");
}
)v8">(R"v8(switch-fallthrough)v8", R"v8(two
three
)v8");
	run_case<R"v8(var n = 0;
do { n++; } while (n < 3);
console.log(n);
)v8">(R"v8(do-while)v8", R"v8(3
)v8");
	run_case<R"v8(console.log("hello".length, "hello"[1], "hello".charCodeAt(0));
)v8">(R"v8(string-length-ascii)v8", R"v8(5 e 104
)v8");
	run_case<R"v8(console.log(parseInt("08"), parseInt("0x10"), parseInt("12px"), parseInt(""));
)v8">(R"v8(shadowed-builtin-parseInt)v8", R"v8(8 16 12 NaN
)v8");
	run_case<R"v8(console.log(String(null), String(undefined), String([1, 2]), String({}));
)v8">(R"v8(tostring-conversions)v8", R"v8(null undefined 1,2 [object Object]
)v8");
	run_case<R"v8(function make() { var count = 0; return function() { count++; return count; }; }
var m = make();
m();
console.log(m(), m());
)v8">(R"v8(nested-closure-counter)v8", R"v8(2 3
)v8");
	std::printf("v8diff: %d failures, %d parse gaps, %d cases\n",
	            failures, parse_gaps, 31);
	return failures == 0 ? 0 : 1;
}
