#!/usr/bin/env python3
"""Generate tests/v8diff.cpp from tests/v8diff.corpus.js.

Each corpus snippet runs under node (V8) NOW to capture the expected
output; the generated TU runs the same snippet under ctjs at test time
and byte-compares. Snippets ctjs cannot parse are compile-time-detected
(ctjs::script_t<Src>::valid) and reported as PARSE-GAP rather than
failing the build. Uncaught throws normalize to "THROWS <Name>: <msg>"
on both sides.
"""
import subprocess
import sys
import re
from pathlib import Path

root = Path(__file__).resolve().parent.parent
corpus = (root / "tests" / "v8diff.corpus.js").read_text(encoding="utf-8")

cases = []  # (name, source)
name = None
lines = []
for line in corpus.splitlines():
    m = re.match(r"^// === (.+)$", line)
    if m:
        if name is not None:
            cases.append((name, "\n".join(lines).strip() + "\n"))
        name = m.group(1).strip()
        lines = []
    elif name is not None and not line.startswith("// ==="):
        lines.append(line)
if name is not None:
    cases.append((name, "\n".join(lines).strip() + "\n"))

def node_expected(src: str) -> str:
    wrapper = (
        "try {\n" + src + "\n} catch (e) {\n"
        "  console.log('THROWS ' + e.name + ': ' + e.message);\n"
        "}\n"
    )
    out = subprocess.run(
        ["node", "--no-warnings", "-e", wrapper],
        capture_output=True, text=True, timeout=15,
    )
    if out.returncode != 0:
        # syntax-level rejection by V8 (should not happen for corpus code)
        return "V8-SYNTAX-ERROR\n"
    return out.stdout

def cxx_escape(s: str) -> str:
    delim = "v8"
    while f"){delim}\"" in s:
        delim += "_"
    return f'R"{delim}({s}){delim}"'

emit = []
emit.append("// GENERATED by tools/gen-v8diff.py - do not edit.")
emit.append("// Expected outputs captured from: " )
node_v = subprocess.run(["node", "--version"], capture_output=True, text=True).stdout.strip()
emit[-1] += node_v
emit.append("#include <ctjs.hpp>")
emit.append("#include <cstdio>")
emit.append("#include <string>")
emit.append("")
emit.append("static int failures = 0;")
emit.append("static int parse_gaps = 0;")
emit.append("")
emit.append("template <ctc::string Src>")
emit.append("static void run_case(const char * name, const char * expected) {")
emit.append("\tif constexpr (!ctjs::script_t<Src>::valid) {")
emit.append("\t\tstd::printf(\"PARSE-GAP %s\\n\", name);")
emit.append("\t\t++parse_gaps;")
emit.append("\t} else {")
emit.append("\t\tauto r = ctjs::script_t<Src>::run({});")
emit.append("\t\tstd::string got{r.console()};")
emit.append("\t\tif (!r.ok()) { got += \"THROWS \" + r.exception_message() + \"\\n\"; }")
emit.append("\t\tif (got != expected) {")
emit.append("\t\t\tstd::printf(\"FAIL %s\\n  v8 : %s  ctjs: %s\", name,")
emit.append("\t\t\t            std::string{expected}.c_str(), got.c_str());")
emit.append("\t\t\t++failures;")
emit.append("\t\t}")
emit.append("\t}")
emit.append("}")
emit.append("")
emit.append("int main() {")
for cname, src in cases:
    expected = node_expected(src)
    emit.append(f"\trun_case<{cxx_escape(src)}>({cxx_escape(cname)}, {cxx_escape(expected)});")
emit.append("\tstd::printf(\"v8diff: %d failures, %d parse gaps, %d cases\\n\",")
emit.append(f"\t            failures, parse_gaps, {len(cases)});")
emit.append("\treturn failures == 0 ? 0 : 1;")
emit.append("}")

(root / "tests" / "v8diff.cpp").write_text("\n".join(emit) + "\n", encoding="utf-8")
print(f"wrote tests/v8diff.cpp with {len(cases)} cases (expected via node {node_v})")
